// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	meta.proto
	overlay.proto
	pointerdb.proto
	piecestore.proto
	bandwidth.proto
	kadcli.proto
	datarepair.proto

It has these top-level messages:
	SegmentMeta
	StreamInfo
	StreamMeta
	LookupRequest
	LookupResponse
	LookupRequests
	LookupResponses
	FindStorageNodesResponse
	FindStorageNodesRequest
	NodeAddress
	OverlayOptions
	NodeRep
	NodeRestrictions
	Node
	QueryRequest
	QueryResponse
	PingRequest
	PingResponse
	Restriction
	RedundancyScheme
	RemotePiece
	RemoteSegment
	Pointer
	PutRequest
	GetRequest
	ListRequest
	PutResponse
	GetResponse
	ListResponse
	DeleteRequest
	DeleteResponse
	IterateRequest
	PayerBandwidthAllocation
	RenterBandwidthAllocation
	PieceStore
	PieceId
	PieceSummary
	PieceRetrieval
	PieceRetrievalStream
	PieceDelete
	PieceDeleteSummary
	PieceStoreSummary
	StatsReq
	StatSummary
	SignedMessage
	AgreementsSummary
	CountNodesResponse
	CountNodesRequest
	InjuredSegment
*/
package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SegmentMeta struct {
	EncryptedKey []byte `protobuf:"bytes,1,opt,name=encrypted_key,json=encryptedKey,proto3" json:"encrypted_key,omitempty"`
	KeyNonce     []byte `protobuf:"bytes,2,opt,name=key_nonce,json=keyNonce,proto3" json:"key_nonce,omitempty"`
}

func (m *SegmentMeta) Reset()                    { *m = SegmentMeta{} }
func (m *SegmentMeta) String() string            { return proto.CompactTextString(m) }
func (*SegmentMeta) ProtoMessage()               {}
func (*SegmentMeta) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{0} }

func (m *SegmentMeta) GetEncryptedKey() []byte {
	if m != nil {
		return m.EncryptedKey
	}
	return nil
}

func (m *SegmentMeta) GetKeyNonce() []byte {
	if m != nil {
		return m.KeyNonce
	}
	return nil
}

type StreamInfo struct {
	NumberOfSegments int64  `protobuf:"varint,1,opt,name=number_of_segments,json=numberOfSegments,proto3" json:"number_of_segments,omitempty"`
	SegmentsSize     int64  `protobuf:"varint,2,opt,name=segments_size,json=segmentsSize,proto3" json:"segments_size,omitempty"`
	LastSegmentSize  int64  `protobuf:"varint,3,opt,name=last_segment_size,json=lastSegmentSize,proto3" json:"last_segment_size,omitempty"`
	Metadata         []byte `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *StreamInfo) Reset()                    { *m = StreamInfo{} }
func (m *StreamInfo) String() string            { return proto.CompactTextString(m) }
func (*StreamInfo) ProtoMessage()               {}
func (*StreamInfo) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{1} }

func (m *StreamInfo) GetNumberOfSegments() int64 {
	if m != nil {
		return m.NumberOfSegments
	}
	return 0
}

func (m *StreamInfo) GetSegmentsSize() int64 {
	if m != nil {
		return m.SegmentsSize
	}
	return 0
}

func (m *StreamInfo) GetLastSegmentSize() int64 {
	if m != nil {
		return m.LastSegmentSize
	}
	return 0
}

func (m *StreamInfo) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type StreamMeta struct {
	EncryptedStreamInfo []byte       `protobuf:"bytes,1,opt,name=encrypted_stream_info,json=encryptedStreamInfo,proto3" json:"encrypted_stream_info,omitempty"`
	EncryptionType      int32        `protobuf:"varint,2,opt,name=encryption_type,json=encryptionType,proto3" json:"encryption_type,omitempty"`
	EncryptionBlockSize int32        `protobuf:"varint,3,opt,name=encryption_block_size,json=encryptionBlockSize,proto3" json:"encryption_block_size,omitempty"`
	LastSegmentMeta     *SegmentMeta `protobuf:"bytes,4,opt,name=last_segment_meta,json=lastSegmentMeta" json:"last_segment_meta,omitempty"`
}

func (m *StreamMeta) Reset()                    { *m = StreamMeta{} }
func (m *StreamMeta) String() string            { return proto.CompactTextString(m) }
func (*StreamMeta) ProtoMessage()               {}
func (*StreamMeta) Descriptor() ([]byte, []int) { return fileDescriptorMeta, []int{2} }

func (m *StreamMeta) GetEncryptedStreamInfo() []byte {
	if m != nil {
		return m.EncryptedStreamInfo
	}
	return nil
}

func (m *StreamMeta) GetEncryptionType() int32 {
	if m != nil {
		return m.EncryptionType
	}
	return 0
}

func (m *StreamMeta) GetEncryptionBlockSize() int32 {
	if m != nil {
		return m.EncryptionBlockSize
	}
	return 0
}

func (m *StreamMeta) GetLastSegmentMeta() *SegmentMeta {
	if m != nil {
		return m.LastSegmentMeta
	}
	return nil
}

func init() {
	proto.RegisterType((*SegmentMeta)(nil), "streams.SegmentMeta")
	proto.RegisterType((*StreamInfo)(nil), "streams.StreamInfo")
	proto.RegisterType((*StreamMeta)(nil), "streams.StreamMeta")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptorMeta) }

var fileDescriptorMeta = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xff, 0xbe, 0xaf, 0x6c, 0x0b, 0x05, 0x03, 0x52, 0x55, 0x2e, 0x28, 0x1c, 0x40, 0x08,
	0xe5, 0x50, 0x5e, 0x00, 0xf5, 0x86, 0x10, 0x54, 0x4a, 0x38, 0x71, 0xb1, 0x9c, 0x74, 0x13, 0x45,
	0x69, 0xec, 0x28, 0x36, 0x07, 0xf7, 0x85, 0x78, 0x2c, 0x5e, 0x05, 0xd9, 0xce, 0x1f, 0x1c, 0x77,
	0x66, 0x34, 0x3b, 0xb3, 0x0b, 0x50, 0xa0, 0x62, 0x7e, 0x59, 0x09, 0x25, 0xc8, 0x7f, 0xa9, 0x2a,
	0x64, 0x85, 0x5c, 0x41, 0x2a, 0x52, 0xe1, 0x40, 0x6f, 0x0b, 0xb3, 0x10, 0xd3, 0x02, 0xb9, 0x7a,
	0x45, 0xc5, 0xc8, 0x0d, 0x1c, 0x23, 0x8f, 0x2b, 0x5d, 0x2a, 0xdc, 0xd1, 0x1c, 0xf5, 0x72, 0x70,
	0x3d, 0xb8, 0x9b, 0x07, 0xf3, 0x16, 0x7c, 0x41, 0x4d, 0xae, 0xe0, 0x28, 0x47, 0x4d, 0xb9, 0xe0,
	0x31, 0x2e, 0x87, 0x56, 0x30, 0xcd, 0x51, 0xbf, 0x99, 0xd9, 0xfb, 0x1a, 0x00, 0x84, 0x76, 0xd1,
	0x33, 0x4f, 0x04, 0x79, 0x00, 0xc2, 0x3f, 0x8b, 0x08, 0x2b, 0x2a, 0x12, 0x2a, 0xdd, 0x26, 0x69,
	0x5d, 0x47, 0xc1, 0xa9, 0x63, 0xb6, 0x49, 0x9d, 0x40, 0x9a, 0xf5, 0x8d, 0x86, 0xca, 0xec, 0xe0,
	0xdc, 0x47, 0xc1, 0xbc, 0x01, 0xc3, 0xec, 0x80, 0xe4, 0x1e, 0xce, 0xf6, 0x4c, 0xaa, 0xc6, 0xcd,
	0x09, 0x47, 0x56, 0xb8, 0x30, 0x44, 0xed, 0x66, 0xb5, 0x2b, 0x98, 0x9a, 0x0b, 0xec, 0x98, 0x62,
	0xcb, 0xb1, 0x4b, 0xda, 0xcc, 0xde, 0x77, 0x9b, 0xd4, 0x56, 0x5f, 0xc3, 0x65, 0x57, 0xdd, 0x9d,
	0x8a, 0x66, 0x3c, 0x11, 0xf5, 0x09, 0xce, 0x5b, 0xb2, 0xd7, 0xee, 0x16, 0x16, 0x35, 0x9c, 0x09,
	0x4e, 0x95, 0x2e, 0x5d, 0xe2, 0x49, 0x70, 0xd2, 0xc1, 0xef, 0xba, 0xc4, 0x9e, 0xb9, 0x11, 0x46,
	0x7b, 0x11, 0xe7, 0x5d, 0xee, 0x49, 0x6b, 0x9e, 0x09, 0xbe, 0x31, 0x9c, 0xcd, 0xfe, 0xf4, 0xa7,
	0xa7, 0x09, 0x6e, 0x4b, 0xcc, 0xd6, 0x17, 0x7e, 0xfd, 0x4b, 0xbf, 0xf7, 0xbc, 0x5f, 0xed, 0x0d,
	0xb0, 0x19, 0x7f, 0x0c, 0xcb, 0x28, 0xfa, 0x67, 0x3f, 0xfd, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0xa7, 0x4c, 0x52, 0x0c, 0x02, 0x00, 0x00,
}
